import colors from '../colors.mjs';

const button = {
	'button-font-family': 'PT Astra Sans',
	'button-font-weight': 400,
	'button-letter-spacing': '1px',
	'button-radius': '4px',
	'button-loading': colors.grey.grey8,
	'button-primary-text': colors.grey.grey1,
	'button-primary-base': colors.teal.teal7,
	'button-primary-hover-text': colors.grey.grey1,
	'button-primary-hover-base': colors.teal.teal5,
	'button-primary-focus-text': colors.grey.grey1,
	'button-primary-focus-base': colors.teal.teal8,
	'button-primary-activ-text': colors.grey.grey1,
	'button-primary-activ-base': colors.teal.teal8,
	'button-secondary-text': colors.teal.teal7,
	'button-secondary-base': 'transparent',
	'button-secondary-border': colors.teal.teal7,
	'button-secondary-hover-text': colors.grey.grey1,
	'button-secondary-hover-base': colors.teal.teal7,
	'button-secondary-hover-border': colors.teal.teal7,
	'button-secondary-focus-text': colors.grey.grey1,
	'button-secondary-focus-base': colors.teal.teal8,
	'button-secondary-focus-border': colors.teal.teal8,
	'button-secondary-activ-text': colors.grey.grey1,
	'button-secondary-activ-base': colors.teal.teal8,
	'button-secondary-activ-border': colors.teal.teal8,
	'button-text-text': colors.teal.teal7,
	'button-text-base': colors.grey.grey1,
	'button-text-hover-text': colors.teal.teal7,
	'button-text-hover-base': colors.grey.grey2,
	'button-text-focus-text': colors.teal.teal7,
	'button-text-focus-base': colors.grey.grey3,
	'button-text-activ-text': colors.teal.teal7,
	'button-text-activ-base': colors.grey.grey3,
	'button-disabled-text': colors.grey.grey5,
	'button-disabled-base': colors.grey.grey2,
	'button-disabled-hover-text': colors.grey.grey5,
	'button-disabled-hover-base': colors.grey.grey2,
	'button-disabled-focus-text': colors.grey.grey5,
	'button-disabled-focus-base': colors.grey.grey2,
	'button-disabled-activ-text': colors.grey.grey5,
	'button-disabled-activ-base': colors.grey.grey2,
	'button-danger-text': colors.grey.grey1,
	'button-danger-base': colors.red.red6,
	'button-danger-hover-text': colors.grey.grey1,
	'button-danger-hover-base': colors.red.red5,
	'button-danger-focus-text': colors.grey.grey1,
	'button-danger-focus-base': colors.red.red7,
	'button-danger-activ-text': colors.grey.grey1,
	'button-danger-activ-base': colors.red.red7,
};
export default button;
